apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aacpp773s-go
  janus-idp.io/tekton: aacpp773s-go
  backstage.io/kubernetes-id: aacpp773s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aacpp773s-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
