apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aacpp773s-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aacpp773s-go 
  name: aacpp773s-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aacpp773s-go 
